version: '2'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=km
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  km:
    image: km
    restart: always
    ports:
      - 8000:3200
    links:
      - mongo
    environment:
      - PORT=3200
      - SALT=your_salt
      - MONGO_USER=root
      - MONGO_PASS=example
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_BASE=km
