version: "2"
services:
  server:
    image: python:alpine
    restart: always
    working_dir: /root
    ports:
      - 5000:5000
    volumes:
      - ./:/root:ro
      - ./app.sqlite:/app.sqlite:rw
    environment:
      - JWT_SALT=your_jwt_salt
      - PWD_SALT=your_password_salt
      - DB_PATH=/app.sqlite
      - FLASK_ENV=development
    entrypoint:
      - sh
      - -c
      - pip install --upgrade pip &&
        pip install --no-cache-dir -r requirements.txt &&
        flask run --host=0.0.0.0 --reload
