name: Python application

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        mv app.sqlite .app.sqlite #TODO: avoid using in test
        pip install pytest
        pytest
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: adapt
      run: |
        sed s@/static/@/km/static/@g static/index.html | sed "s@path: '@path:'/km@g" > 404.html
        rm *.py *.md *.sqlite *.txt *yml
        find
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./
